entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

#Change the 0 to 1 and nothing higher. 0 = Disabled 1 = Allow them to spawn
max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cow: 1
  creeper: 0
  enderman: 0
  ghast: 0
  husk: 0
  horse: 0
  mooshroom: 0
  ocelot: 0
  pig: 1
  polarbear: 1
  rabbit: 1
  stray: 0 
  sheep: 1
  skeleton: 0
  spider: 0
  wolf: 0
  zombie: 0
