version: 2
jobs:
  build:
    
    working_directory: ~/MobPlugin

    docker:
      - image: cimg/openjdk:8.0

    steps:

      - checkout

      - restore_cache:
          key: MobPlugin-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: MobPlugin-{{ checksum "pom.xml" }}
      
      - run: mvn clean package
